# Generated by Django 3.1.2 on 2020-11-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='geeksmodel',
            name='last_modified',
        ),
    ]
